### ISSUE TITLE
Numpy array in ModelVariable's result

### ISSUE THREAD

**Issue by zchmielewska** [acturtle/cashflower#110]
cashflow.py
```
        self.result = np.empty((self.modelpoint.size, t_calculation_max+1), dtype=float)

        for r in range(self.modelpoint.size):
            self.clear()
            self.modelpoint.record_num = r

            if self.recursive == "not_recursive":
                self.result[r, :] = [*map(self.formula, range(t_calculation_max+1))]
```

self.result is initiated as np array but afterways it's overwritten with "normal" array - there is no point in that.

In the last line add `np.array( ... )`. 

Perhaps no point in initializing an array at all because we are replacing the whole array later on.

**Comment by acturtle** [comment]
This is not true.

Firstly, we initialize empty multidimensional array n x m, where n is number of periods and m number of records in the modelpoint file.

In the calculation, we replace the inner list which gets converted automatically into numpy array.

For example:

```
x = np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

x[1, :] = [1,2,3]

array([[0., 0., 0.],
       [1., 2., 3.]])

type(x)
numpy.ndarray
```
