### ISSUE TITLE
Generic framework

### ISSUE THREAD

**Issue by zchmielewska** [acturtle/cashflower#113]
Currently, the framework is thought for liabilities but it could be easily used for assets too.

To make it more generic, we should change some of the vocabulary we use. 

I propose:
- `policy` --> `modelpoint` - we call the main input policy but it could also contain list of assets. So it's better to use something generic.
- `policy_id` --> `id` - similar to above, to get rid off being dependent on the word "policy", we can call the key column simply "id" which is more general and as informative.

**Comment by acturtle** [comment]
Also, the attribute of ModelVariable called `pol_dep` should be renamed to e.g. `mp_dep`.

**Comment by acturtle** [comment]
Maybe:

policy --> primary

because modelpoint is already a name of the class.

**Comment by zchmielewska** [comment]
To do:
- [ ] rename `policy` model point to `main` everywhere in the code (templates + code + logs)
- [ ] rename `pol_dep` attribute of ModelVariable to `mp_dep`
- [ ] rename `policy_id` to `id` as the column name over which iteration takes place
- [ ] update README
- [ ] update tutorials
- [ ] update blog posts
- [ ] change version by increasing major

**Comment by zchmielewska** [comment]
Other tasks:
- [ ] update /31/graph.png
- [ ] update /34/graph.png
