### ISSUE TITLE
[DEV] Numpy matrices for policy outputs

### ISSUE THREAD

**Issue by acturtle** [acturtle/cashflower#122]
Policy outputs are currently stored in dictionary of data frames.

Perhaps it's better to store them as numpy arrays.

Probably we need separate for floats and strings.

Add column names just before saving.

**Comment by zchmielewska** [comment]
What about runtime output?

**Comment by zchmielewska** [comment]
`feature/matrix`

**Comment by zchmielewska** [comment]
What is sb chooses a column that is a constant and the output is aggregated?

**Comment by zchmielewska** [comment]
Done in 0951d34beaf835d77499528b144b06957a2170af
