### ISSUE TITLE
Create variables that are independent from t

### ISSUE THREAD

**Issue by zchmielewska** [acturtle/cashflower#13]
There are scalar variables that have the same value for all periods

There is no need to calculate its value independently for each of the periods

**Comment by zchmielewska** [comment]
e.g. of a variable: elapsed_months

**Comment by acturtle** [comment]
There are two possibilities:
- create an independent class for scalars (variables independent of t),
- still use ModelVariable class.

For example, if you have the same expense value for each month which you read from an assumption table, you can do it the following way:

```python
expense = ModelVariable()

@assign(expense)
def expense_formula(t):
    if t == 0:
       return <read-from-assumptions-table>
   return expense(t-1)
```

In that way, we only read from a table once (which is computationally expensive operation) and then only read the value from the previous period.

In that way, we don't have to introduce any other class (e.g. `ModelScalar`). Fewer classes means simpler code.

However, we should check if introducing a scalar would help with speed. If so, then it might be worth to introduce it.

So thanks for this suggestion, I'll check it and get back to you.

**Comment by acturtle** [comment]
The functionality has been impemented in https://github.com/acturtle/cashflower/commit/b6bb2bede4c5ee816e00aba1972f0400b81c8b71

It has been implemented as new attribute of ModelVariable called `scalar`.

For example:
```
bar = ModelVariable(modelpoint=policy, scalar=True)

@assign(bar)
def bar_formula():
    return assumption["table"].loc[657]["B"]
```

Note that the formula doesn't have a parameter `t`.
