### ISSUE TITLE
[DEV] Limit calculation when columns are chosen

### ISSUE THREAD

**Issue by zchmielewska** [acturtle/cashflower#20]
If the user chooses columns then limit calculation so that we don't calculate unnecessary columns

**Comment by acturtle** [comment]
For example we have the following "tree":
```
a --> b, c
b --> d, e, f
e --> g
```
User wants only results for b.

- Model must calculate b, d, e, f, g.
- Model doesn't have to calculate a and c.

**Comment by zchmielewska** [comment]
Done in 837f0d9f7283c749e9b59e0a07699139db724dbf
