### ISSUE TITLE
Rename cashflow.py to core.py

### ISSUE THREAD

**Issue by acturtle** [acturtle/cashflower#304]

**Comment by zchmielewska** [comment]
Rationale:

While it's not a strict requirement, naming one of the main scripts in a Python package "core.py" is a common convention. The use of "core.py" as a module name is often seen in packages to signify that it contains fundamental functionality and serves as the central module of the package.

**Comment by zchmielewska** [comment]
Done in 7beeac2d27398633f9c6b70f3b26c0bed9897437
