### ISSUE TITLE
Runtime ideas

### ISSUE THREAD

**Issue by zchmielewska** [acturtle/cashflower#31]
Use numpy more

Make policy_id column an index

Vectorize easy formula e.g. a + b could be vectorized

Check recursive functions

**Comment by zchmielewska** [comment]
Recursiveness naive idea:

 @property
    def name(self):
        return self._name

    @name.setter
    def name(self, new_name):
        self._name = new_name
        formula_source = inspect.getsource(self.formula)
        if new_name+"(t+1)" in formula_source or new_name+"(t + 1)" in formula_source:
            self.post_recursive = True


            if not self.post_recursive:
                # The try-except formula helps with autorecursive functions
                try:
                    self.result[r] = list(map(self.formula, range(t_calculation_max+1)))
                except RecursionError:
                    lst = list(map(self.formula, range(t_calculation_max, -1, -1)))
                    lst.reverse()
                    self.result[r] = lst
            else:
                try:
                    lst = list(map(self.formula, range(t_calculation_max, -1, -1)))
                    lst.reverse()
                    self.result[r] = lst
                except RecursionError:
                    self.result[r] = list(map(self.formula, range(t_calculation_max + 1)))

**Comment by acturtle** [comment]
The framework identifies recursive functions now.
