### ISSUE TITLE
Aggregate by groups

### ISSUE THREAD

**Issue by zchmielewska** [acturtle/cashflower#316]
### Discussed in https://github.com/acturtle/cashflower/discussions/90

<div type='discussions-op-text'>

<sup>Originally posted by **zchmielewska** August 17, 2022</sup>
Now we have options:
- don't aggregate at all
- aggregate for all policies

What about aggregating for groups?</div>

**Comment by kyworkact** [comment]
Hi, thanks a lot for creating this package. I had used it to create some projections and it was not too hard to understand the flow to navigate through the whole process. The diagnostics output also helps in double-checking the projection logics. It's really a great package! For the aggregation, I think it would be very useful to have it for groups. I was wondering if you would consider allowing group indicator at the policy data level that can be recognized by cashflower for the aggregation? Thanks!

**Comment by acturtle** [comment]
Hi @kyworkact , thank you for your kind words about the package! Yes, definitely aggregating by groups is the feature that will be implemented. We will prioritize it since you find it useful. We will notify you once it's finished. If you have any more suggestions, please feel to share!

**Comment by zchmielewska** [comment]
Maybe there should be an additional setting in `settings.py`, e.g. `GROUP_VARIABLE` or `GROUPING_VARIABLE`. 
And then there would be 3 possibilities:

[1] Aggregates by all model points
```
settings = {
    "AGGREGATE": True,
    "GROUP_VARIABLE": None,
}
```

[2] Aggregates by group variable (here `product_code`)
```
settings = {
    "AGGREGATE": True,
    "GROUP_VARIABLE": "product_code",
}
```

[3] No aggregation, individual output (value of `GROUP_VARIABLE` - if any - is then ignored)
```
settings = {
    "AGGREGATE": False,
}
```

Few thoughts/considerations:

- there must be a check that the grouping variable is part of the `main` model point set,
- commercial software (and I think both RAFM and Prophet) usually requires model points to be sorted by grouping variable - what should be the approach here.

**Comment by kyworkact** [comment]
> Owner

Thanks in advance! I think if a goal seek function is available similar to what excel has, it would be very useful e.g. for generating premium rate in meeting certain profit target. Thanks!

**Comment by zchmielewska** [comment]
Goal seeking function is a very interesting idea! Thanks for sharing.

**Comment by zchmielewska** [comment]
Hi @kyworkact, aggregating by groups has been introduced in version 0.5.7 of the package. 
You can specify the group indicator at the policy data level using the `GROUP_BY_COLUMN` setting in the configuration.

Here's an example of how to use this feature:

input.py
```python
main = ModelPointSet(data=pd.DataFrame({
    "id": [1, 2, 3, 4],
    "code": ["A", "B", "A", "C"]
}))
```

settings.py
```python
settings = {
    "AGGREGATE": True,
    "GROUP_BY_COLUMN": "code",
    ...
}

```

output
```
    t code  my_var
0   0    A     0.0
1   1    A     2.0
2   2    A     4.0
3   3    A     6.0
4   0    B     0.0
5   1    B     1.0
6   2    B     2.0
7   3    B     3.0
8   0    C     0.0
9   1    C     1.0
10  2    C     2.0
11  3    C     3.0
```

If you have any questions or if there are any problems with this feature, please let me know.

**Comment by kyworkact** [comment]
Thanks a lot for notifying for this new feature. Will definitely check it out.

**Comment by kyworkact** [comment]
It works as expected for the projection I did. Thanks a lot again!

**Comment by zchmielewska** [comment]
Great! Glad to hear it and thanks for the information. If you ever need anything else, just let us know!
