### ISSUE TITLE
Log name of model and progressbar

### ISSUE THREAD

**Issue by acturtle** [acturtle/cashflower#46]
Now log shows

```
15:06:02 | Run started
15:06:02 | Run finished
```

but if I have multiple models then it's not obvious which one I have started.

It would be good to state the name of the model that was run, created files and progressbar.

**Comment by zchmielewska** [comment]
Done in https://github.com/acturtle/cashflower/commit/f65460219277a8997b1f7c1ed8761bc843d85dfa
