### ISSUE TITLE
[TEST] Data mismatches

### ISSUE THREAD

**Issue by zchmielewska** [acturtle/cashflower#63]
- [ ] 1 - other model point has no corresponging policy id
- [x] 2 - version does not exist
- [x] 3 - column is chosen which does not exist

**Comment by zchmielewska** [comment]
Ad 3: Nothing will happen, it will simply be ignored.

**Comment by zchmielewska** [comment]
Ad 2: Done in 7ce599974cd669ae742b825470deff7219d4a360

**Comment by acturtle** [comment]
Ad 1: Done in 15d092eb8be7337b12a82267e74cdcde3b30c3d8
